apps/news_hunter/urls.py
from django.conf.urls import url

from . import views

app_name = 'news_hunter'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add/$', views.HuntCreateView.as_view(), name='hunt_create'),
    url(r'^(?P<pk>\d+)/edit/$', views.HuntUpdateView.as_view(), name='hunt_edit'),
    url(r'^(?P<pk>\d+)/csv/$', views.hunt_export, name='hunt_export'),
    url(r'^(?P<pk>\d+)/switch_notice/$', views.hunt_switch_notice, name='hunt_switch_notice'),
    url(r'^(?P<pk>\d+)/switch_enable/$', views.hunt_switch_enable, name='hunt_switch_enable'),
    url(r'^(?P<pk>\d+)/$', views.NewsListView.as_view(), name='news_list'),
]

apps/news_hunter/models.py
from django.db import models
from django.utils import timezone
import subprocess
from apps.news.models import News


class Hunt(models.Model):
    id = models.AutoField(primary_key=True)
    datetime = models.DateTimeField(default=timezone.now)
    name = models.CharField(max_length=255)
    keyword = models.CharField(max_length=255)
    notice = models.BooleanField(default=False)
    channel = models.CharField(max_length=255, null=True, blank=True)
    enable = models.BooleanField(default=True)
    newss = models.ManyToManyField(News)

    def __str__(self):
        return str(self.id)

    def setDisable(self):
        self.enable = False
        self.save()

    def setEnable(self):
        self.enable = True
        self.save()

    def setNoticeTrue(self):
        self.notice = True
        self.save()

    def setNoticeFalse(self):
        self.notice = False
        self.save()

    def run(self):
        cmd = "python scripts/hunter/news/nw_hunter.py " + str(self.id)
        subprocess.Popen(cmd, shell=True)

apps/news_hunter/forms.py
from django.forms import ModelForm, CharField
from django.utils.translation import ugettext_lazy as _
from .models import Hunt

def popover_html(label, content):
        return label + ' <a role="button" data-toggle="tooltip" data-placement="auto" title="' + content + '"><i class="fas fa-info-circle"></i></a>'

class HuntForm(ModelForm):
    class Meta:
        model = Hunt
        fields = ('name', 'keyword', 'channel', 'notice', )
        labels = {
                'notice': popover_html('slack notice', "Slack will be notified if checked."),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['keyword'].widget.attrs['placeholder'] = "e.g. 'apt1 osint' is apt1 AND osint, and 'apt1,osint' is apt1 OR osint"
        self.fields['channel'].widget.attrs['placeholder'] = "slack channel name. default is th-[Name]."

apps/news_hunter/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from pure_pagination.mixins import PaginationMixin
from django.db.models import Q, Count
from .models import Hunt
from apps.news.models import News
from .forms import HuntForm
import csv
from io import StringIO, BytesIO
from codecs import BOM_UTF8
from pytz import timezone
from django.http import JsonResponse
from urllib.parse import urlparse
from http.client import HTTPConnection

class IndexView(PaginationMixin, ListView):
    model = Hunt
    template_name = 'news_hunter/index.html'
    context_object_name = 'hunts'
    paginate_by = 30

    def get_queryset(self):
        query = Hunt.objects.order_by('id')
        query = query.annotate(count=Count('newss'))
        return query

    def post(self, request, *args, **kwargs):
        hunt_id = request.POST['delete']
        hunt = get_object_or_404(Hunt, id=hunt_id)
        hunt.delete()
        return redirect('news_hunter:index')

class NewsListView(PaginationMixin, ListView):
    model = News
    template_name = 'news_hunter/news_list.html'
    context_object_name = 'newss'
    paginate_by = 30

    def get_queryset(self, pk):
        pk = self.kwargs['pk']
        query = News.objects.filter(Q(id__in=Hunt(id=pk).newss.all())).order_by('-datetime')
        return query

    def get(self, request, pk):
        self.object_list = self.get_queryset(pk)
        context = self.get_context_data()
        return render(request, 'news_hunter/news_list.html', context)

class HuntCreateView(CreateView):
    model = Hunt
    form_class = HuntForm
    template_name = 'news_hunter/hunt_form.html'

    def get_success_url(self):
        self.object.run()
        return '/news_hunter'

class HuntUpdateView(UpdateView):
    model = Hunt
    form_class = HuntForm
    template_name = 'news_hunter/hunt_edit_form.html'

    def get_success_url(self):
        self.object.run()
        return '/news_hunter'

def hunt_export(request, pk):
    stream = StringIO()
    writer = csv.writer(stream)
    header = ['#datetime', 'title', 'referrer', 'source_title']
    writer.writerow(header)
    for news in News.objects.filter(id__in=Hunt(id=pk).newss.all()).order_by('datetime'):
        dt = news.datetime.astimezone(timezone('Asia/Tokyo'))
        row = [dt, news.title, news.referrer, news.source_title]
        writer.writerow(row)
    b_stream = BytesIO(BOM_UTF8 + stream.getvalue().encode('utf8'))
    response = HttpResponse(b_stream.getvalue(), content_type="text/csv")
    response["Content-Disposition"] = "filename=hunter%s.csv" % pk
    return response

def hunt_switch_notice(request, pk):
    hunt = get_object_or_404(Hunt, id=pk)
    if hunt.notice == True:
        hunt.setNoticeFalse()
    else:
        hunt.setNoticeTrue()
    hunt.run()
    return redirect('news_hunter:index')

def hunt_switch_enable(request, pk):
    hunt = get_object_or_404(Hunt, id=pk)
    if hunt.enable == True:
        hunt.setDisable()
    else:
        hunt.setEnable()
        hunt.run()
    return redirect('news_hunter:index')

apps/news_hunter/templates/news_hunter/hunt_edit_form.html
{% extends "base.html" %}

{% block content %}
{% load bootstrap4 %}
{% load static %}
<div class="container">
    <h1 class="my-4">Edit Hunter</h1>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <div align="right">
        <a href="{% url 'threat_hunter:index' %}" class="btn btn-secondary">Back</a>
    </div>
</div>
{% endblock %}

apps/news_hunter/templates/news_hunter/hunt_form.html
{% extends "base.html" %}

{% block content %}
{% load bootstrap4 %}
{% load static %}
<div class="container">
    <h1 class="my-4">Create New Hunter</h1>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <div align="right">
        <a href="{% url 'threat_hunter:index' %}" class="btn btn-secondary">Back</a>
    </div>
</div>
{% endblock %}

apps/news_hunter/templates/news_hunter/index.html
{% extends "base.html" %}

{% block content %}
{% load humanize %}
{% load static %}
<div class="container col-sm-10">
    <h1 class="my-4">News Hunter</h1>
    <a class="btn btn-outline-primary my-2" href="{% url 'news_hunter:hunt_create' %}" role="button" data-toggle="tooltip" data-placement="bottom" title="Create new hunter">Add</a>
    <table class="table table-responsive table-hover" style="table-layout:fixed;width:100%;">
        <thead>
            <tr>
                <th style="width:50px;"></th>
                <th style="width: 100px;">On/Off</th>
                <th style="width: 200px;">Added Date (JST)</th>
                <th style="width: 100px;">ID</th>
                <th>Name</th>
                <th>Keyword</th>
                <th style="width:150px;">Notice (slack)</th>
                <th style="width:100px;">Hits</th>
                <th style="width:120px;"></th>
                <th style="width:100px;"></th>
            </tr>
        </thead>
        <tbody>
        {% for ht in hunts %}
        {% if ht.enable %}
        <tr>
        {% else %}
        <tr class="table-secondary">
        {% endif %}
            <td><a class="btn btn-outline-secondary btn-sm" href="{% url 'news_hunter:hunt_edit' ht.id %}" role="button"><i class="fas fa-edit"></i></a></td>
            <td>
                <form method="post" action="{% url 'news_hunter:hunt_switch_enable' pk=ht.id %}">
                    {% csrf_token %}
                    <label class="switch-light switch-material" onclick="this.form.submit()">
                        {% if ht.enable %}
                        <input type="checkbox" checked="checked">
                        {% else %}
                        <input type="checkbox">
                        {% endif %}
                        <span>
                            <span>Off</span>
                            <span>On</span>
                            <a></a>
                        </span>
                    </label>
                </form>
            </td>
            <td nowrap>{{ ht.datetime }}</td>
            <td>{{ ht.id }}</td>
            <td><a href="{% url 'news_hunter:news_list' pk=ht.id %}">{{ ht.name }}</a></td>
            <td>{{ ht.keyword }}</td>
            <td>
                <form method="post" action="{% url 'news_hunter:hunt_switch_notice' pk=ht.id %}">
                    {% csrf_token %}
                    <label class="switch-light switch-material" onclick="this.form.submit()">
                        {% if ht.notice %}
                        <input type="checkbox" checked="checked">
                        {% else %}
                        <input type="checkbox">
                        {% endif %}
                        <span>
                            <span>Off</span>
                            <span>On</span>
                            <a></a>
                        </span>
                    </label>
                </form>
            </td>
            <td>{{ ht.count | intcomma }}</td>
            <td><a class="btn btn-outline-success btn-sm" href="{% url 'news_hunter:hunt_export' pk=ht.id %}" role="button">Export CSV</a></td>
            <td><button type="button" class="btn btn-outline-danger btn-sm" data-toggle="modal" data-target="#deleteModal{{ ht.id }}">Delete</button>
                <div class="modal fade" id="deleteModal{{ ht.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel{{ ht.id }}" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel{{ ht.id }}">Delete Hunter</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Are you sure you want to delete hunter "{{ ht.name }}" ?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <form action="" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="delete" value={{ ht.id }}>
                                    <input type="submit" value="Delete" class="btn btn-danger"/>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% include "news_hunter/page.html" %}
</div>
{% endblock %}

{% block javascript %}
<script>
$(function () {
    $('[data-toggle="tooltip"]').tooltip()
})
</script>
{% endblock %}

apps/news_hunter/templates/news_hunter/news_list.html
{% extends "base.html" %}

{% block content %}
{% load humanize %}
{% load static %}
<p class="text-right"> Events: {{ count| intcomma }} </p>
<table class="table table-sm table-responsive table-hover" style="table-layout:fixed;width:100%;">
    <thead>
        <tr>
            <th style="width: 200px;">Date (JST)</th>
            <th style="width: 400px;">Title</th>
            <th>Content</th>
        </tr>
    </thead>
    <tbody>
    {% for nw in newss %}
    <tr>
        <td nowrap>{{ nw.datetime }}</td>
        <td>
            <a href="{{ nw.referrer }}" target="blank">{{ nw.title }}</a><br>
            <a href="{{ nw.source_url }}" class="font-italic small text-black-50" target="blank">{{ nw.source_title }}</a>
        </td>
        <td>{{ nw.content|striptags|truncatewords:30 }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% include "news_hunter/page.html" %}
{% endblock %}

apps/news_hunter/templates/news_hunter/page.html
{% if is_paginated %}
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="{{ request.path }}?{{ page_obj.previous_page_number.querystring }}">previous</a></li>
        {% endif %}
        {% for link_page in page_obj.pages %}
            {% if link_page %}
                {% if link_page == page_obj.number %}
                <li class="page-item active">
                    <span class="page-link">
                        {{ link_page }}
                        <span class="sr-only">(current)</span>
                    </span>
                </li>
                {% else %}
                <li class="page-item"><a class="page-link" href="{{ request.path }}?{{ link_page.querystring  }}">{{ link_page }}</a></li>
                {% endif %}
            {% else %}
                {# 省略された部分の表示内容 #}
                <li class="page-item disabled">...</li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="{{ request.path }}?{{ page_obj.next_page_number.querystring }}">next</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}