apps/threat_hunter/urls.py
from django.conf.urls import url

from . import views

app_name = 'threat_hunter'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add/$', views.HuntCreateView.as_view(), name='hunt_create'),
    url(r'^(?P<pk>\d+)/edit/$', views.HuntUpdateView.as_view(), name='hunt_edit'),
    url(r'^(?P<pk>\d+)/csv/$', views.hunt_export, name='hunt_export'),
    url(r'^(?P<pk>\d+)/switch_notice/$', views.hunt_switch_notice, name='hunt_switch_notice'),
    url(r'^(?P<pk>\d+)/switch_enable/$', views.hunt_switch_enable, name='hunt_switch_enable'),
    url(r'^(?P<pk>\d+)/$', views.EventListView.as_view(), name='event_list'),
]

apps/threat_hunter/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from pure_pagination.mixins import PaginationMixin
from django.db.models import Q, Count
from .models import Hunt
from apps.threat.models import Event
from .forms import HuntForm
import csv
from io import StringIO, BytesIO
from codecs import BOM_UTF8
from pytz import timezone
from django.http import JsonResponse
from urllib.parse import urlparse
from http.client import HTTPConnection

class IndexView(PaginationMixin, ListView):
    model = Hunt
    template_name = 'threat_hunter/index.html'
    context_object_name = 'hunts'
    paginate_by = 30

    def get_queryset(self):
        query = Hunt.objects.order_by('id')
        query = query.annotate(count=Count('events'))
        return query

    def post(self, request, *args, **kwargs):
        hunt_id = request.POST['delete']
        hunt = get_object_or_404(Hunt, id=hunt_id)
        hunt.delete()
        return redirect('threat_hunter:index')

class EventListView(PaginationMixin, ListView):
    model = Event
    template_name = 'threat_hunter/event_list.html'
    context_object_name = 'events'
    paginate_by = 30

    def get_queryset(self, pk):
        pk = self.kwargs['pk']
        query = Event.objects.filter(Q(id__in=Hunt(id=pk).events.all())).order_by('-publish_timestamp')
        return query

    def get(self, request, pk):
        self.object_list = self.get_queryset(pk)
        context = self.get_context_data()
        return render(request, 'threat_hunter/event_list.html', context)

class HuntCreateView(CreateView):
    model = Hunt
    form_class = HuntForm
    template_name = 'threat_hunter/hunt_form.html'

    def get_success_url(self):
        self.object.run()
        return '/threat_hunter'
        
class HuntUpdateView(UpdateView):
    model = Hunt
    form_class = HuntForm
    template_name = 'threat_hunter/hunt_edit_form.html'

    def get_success_url(self):
        self.object.run()
        return '/threat_hunter'

def hunt_export(request, pk):
    stream = StringIO()
    writer = csv.writer(stream)
    header = ['#published', 'date', 'info', 'level', 'attribute_count', 'org']
    writer.writerow(header)
    for event in Event.objects.filter(id__in=Hunt(id=pk).events.all()).order_by('publish_timestamp'):
        dt = event.publish_timestamp.astimezone(timezone('Asia/Tokyo'))
        row = [dt, event.date, event.info, event.get_threat_level_id_display(), event.attribute_count, event.org.name]
        writer.writerow(row)
    b_stream = BytesIO(BOM_UTF8 + stream.getvalue().encode('utf8'))
    response = HttpResponse(b_stream.getvalue(), content_type="text/csv")
    response["Content-Disposition"] = "filename=hunter%s.csv" % pk
    return response

def hunt_switch_notice(request, pk):
    hunt = get_object_or_404(Hunt, id=pk)
    if hunt.notice == True:
        hunt.setNoticeFalse()
    else:
        hunt.setNoticeTrue()
    hunt.run()
    return redirect('threat_hunter:index')

def hunt_switch_enable(request, pk):
    hunt = get_object_or_404(Hunt, id=pk)
    if hunt.enable == True:
        hunt.setDisable()
    else:
        hunt.setEnable()
        hunt.run()
    return redirect('threat_hunter:index')

apps/threat_hunter/templates/threat_hunter/index.html
{% extends "base.html" %}

{% block content %}
{% load humanize %}
{% load static %}
<div class="container col-sm-10">
    <h1 class="my-4">Threat Hunter</h1>
    <a class="btn btn-outline-primary my-2" href="{% url 'threat_hunter:hunt_create' %}" role="button" data-toggle="tooltip" data-placement="bottom" title="Create new hunter">Add</a>
    <table class="table table-responsive table-hover" style="table-layout:fixed;width:100%;">
        <thead>
            <tr>
                <th style="width:50px;"></th>
                <th style="width: 100px;">On/Off</th>
                <th style="width: 200px;">Added Date (JST)</th>
                <th style="width: 100px;">ID</th>
                <th>Name</th>
                <th>Keyword</th>
                <th style="width:150px;">Notice (slack)</th>
                <th style="width:100px;">Hits</th>
                <th style="width:120px;"></th>
                <th style="width:100px;"></th>
            </tr>
        </thead>
        <tbody>
        {% for ht in hunts %}
        {% if ht.enable %}
        <tr>
        {% else %}
        <tr class="table-secondary">
        {% endif %}
            <td><a class="btn btn-outline-secondary btn-sm" href="{% url 'threat_hunter:hunt_edit' ht.id %}" role="button"><i class="fas fa-edit"></i></a></td>
            <td>
                <form method="post" action="{% url 'threat_hunter:hunt_switch_enable' pk=ht.id %}">
                    {% csrf_token %}
                    <label class="switch-light switch-material" onclick="this.form.submit()">
                        {% if ht.enable %}
                        <input type="checkbox" checked="checked">
                        {% else %}
                        <input type="checkbox">
                        {% endif %}
                        <span>
                            <span>Off</span>
                            <span>On</span>
                            <a></a>
                        </span>
                    </label>
                </form>
            </td>
            <td nowrap>{{ ht.datetime }}</td>
            <td>{{ ht.id }}</td>
            <td><a href="{% url 'threat_hunter:event_list' pk=ht.id %}">{{ ht.name }}</a></td>
            <td>{{ ht.keyword }}</td>
            <td>
                <form method="post" action="{% url 'threat_hunter:hunt_switch_notice' pk=ht.id %}">
                    {% csrf_token %}
                    <label class="switch-light switch-material" onclick="this.form.submit()">
                        {% if ht.notice %}
                        <input type="checkbox" checked="checked">
                        {% else %}
                        <input type="checkbox">
                        {% endif %}
                        <span>
                            <span>Off</span>
                            <span>On</span>
                            <a></a>
                        </span>
                    </label>
                </form>
            </td>
            <td>{{ ht.count | intcomma }}</td>
            <td><a class="btn btn-outline-success btn-sm" href="{% url 'threat_hunter:hunt_export' pk=ht.id %}" role="button">Export CSV</a></td>
            <td><button type="button" class="btn btn-outline-danger btn-sm" data-toggle="modal" data-target="#deleteModal{{ ht.id }}">Delete</button>
                <div class="modal fade" id="deleteModal{{ ht.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel{{ ht.id }}" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel{{ ht.id }}">Delete Hunter</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Are you sure you want to delete hunter "{{ ht.name }}" ?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <form action="" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="delete" value={{ ht.id }}>
                                    <input type="submit" value="Delete" class="btn btn-danger"/>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% include "threat_hunter/page.html" %}
</div>
{% endblock %}

{% block javascript %}
<script>
$(function () {
    $('[data-toggle="tooltip"]').tooltip()
})
</script>
{% endblock %}