apps/acti/urls.py
# from django.urls import path
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = 'acti'
urlpatterns = [
    url(r'^$',views.index, name='index'),  # インデックス
    url(r'^add/$', views.tweet_add, name="tweet_add"),
    url(r'^get/$',views.tweet_get, name="tweet_get"),
    url(r'^tweet/',include([
        url(r'add_annotation/$',views.annotation, name='add_annotation'),
        url(r'annotation/(?P<tweet_id>[0-9]+)/$', views.tweet_edit, name='tweet_annotation'),
        url(r'view/(?P<tweet_id>[0-9]+)/$', views.tweet_view, name='tweet_view'),
        url(r'(?P<mode>.+)/$', views.TweetList.as_view(), name='tweet_list'),
    ])),
    url(r'^label/',include([
        url(r'add_label/$', views.add_label, name='add_label'),
        url(r'delete_label/$', views.delete_label, name='delete_label'),
    ])),
    url(r'^download/$', views.export_annotation, name='download'),
]

apps/acti/templates/acti/menu.html
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a href="{% url 'acti:tweet_list' mode='check' %}" class="navbar-brand">ACTI</a>
    <button class="navbar-toggler" type="button"
        data-toggle="collapse"
        data-target="#navmenu1"
        aria-controls="navmenu1"
        aria-expanded="false"
        aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navmenu1">
      <div class="navbar-nav">
        <a class={% if mode == 'check' %}"active nav-item nav-link"{% else %}"nav-item nav-link"{% endif %}  href="{% url 'acti:tweet_list' mode='check' %}">Unannotated targets</a>
        <a class={% if mode == 'already' %}"active nav-item nav-link"{% else %}"nav-item nav-link"{% endif %} href="{% url 'acti:tweet_list' mode='already' %}">Annotated targets</a>
        <a class={% if mode == 'all' %}"active nav-item nav-link"{% else %}"nav-item nav-link"{% endif %} href="{% url 'acti:tweet_list' mode='all' %}">All targets</a>
        <a class="nav-item nav-link" href="{% url 'acti:download' %}">Export CSV</a>
      </div>
    </div>
  </nav>

apps/acti/templates/acti/page.html
{% if is_paginated %}
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item shadow"><a class="page-link" href="{{ request.path }}?{{ page_obj.previous_page_number.querystring }}">previous</a></li>
        {% endif %}
        {% for link_page in page_obj.pages %}
            {% if link_page %}
                {% if link_page == page_obj.number %}
                <li class="page-item active shadow">
                    <span class="page-link">
                        {{ link_page }}
                        <span class="sr-only">(current)</span>
                    </span>
                </li>
                {% else %}
                <li class="page-item shadow"><a class="page-link" href="{{ request.path }}?{{ link_page.querystring  }}">{{ link_page }}</a></li>
                {% endif %}
            {% else %}
                {# 省略された部分の表示内容 #}
                <li class="page-item disabled">...</li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item shadow"><a class="page-link" href="{{ request.path }}?{{ page_obj.next_page_number.querystring }}">next</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}

apps/acti/templates/acti/tweet_edit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}ACTI{% endblock title %}

{% block content %}
{% include "acti/menu.html" %}
	<div id="main" class="container">
		<app></app>
	</div>

	<script type="text/javascript">
		var text = "{{ text|safe|escapejs }}";
		var labels = {{ labels|safe|escape }};
		var annotation = {{ annotation|safe|escape }};
		var post_url = "{% url "acti:add_annotation" %}";
		var post_url_label_delete = "{% url "acti:delete_label" %}";
		var post_url_label_add = "{% url "acti:add_label" %}";
		const twkey = "{{tweet_id}}";
	</script>

	<script type="text/x-template" id="app-header-button-template">
		<div class="m-1">
			<button class="btn btn-sm" style="font-weight: bold;" :style="styleColor" @click="clickedlabel">[[ labelName ]]</button>
			<a v-if="edit" @click="removeLabel" aria-label="Close" class="text-danger" style="cursor:pointer;"><span aria-hidden="true">&times;</span></a>
		</div>
	</script>

	<script type="text/x-template" id="app-header-editmodal-template">
		<div class="row justify-content-end px-1">
			<button id="show-modal" class="btn btn-info" data-toggle="modal" data-target="#modal1">Edit Labels</button>
			<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="label1" aria-hidden="true">
				<div class="modal-dialog" role="document">
					<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title" id="label1">Edit Labels</h5>
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
						</div>
						<div class="modal-body">
							<div class="row m-2">
								<p>Add Labels</p>
								<div class="row">
									<div class="col-7 align-self-center">
										<div class="d-flex flex-row">
											<input class="mx-1" v-model="labelName" :style="styleColor" placeholder="Label Name">
										</div>
									</div>
									<div class="col-5 dropdown">
									  <button type="button" id="dropdown1"
										  class="btn btn-secondary dropdown-toggle"
										  data-toggle="dropdown"
										  aria-haspopup="true"
										  aria-expanded="false">
										  select-color
									  </button>
									  <div class="dropdown-menu" aria-labelledby="dropdown1">
										  <div class="card-columns">
												<div v-for="color in colors" class="card" :style="{background: color}" @click="setNowColor(color)">
													<div class="card-body"></div>
												</div>
										  </div>
									  </div>
									</div>
								</div>
							</div>
							<button class="m-1 btn btn-primary" @click="addLabelSave" data-dismiss="modal" aria-label="Close">Save</button>
							<div class="mt-3 mx-2">
								<div class="d-block">
									<p>Delete Labels</p>
								</div>
								<div class="row">
									<app-header-button v-for="label in labels" :labelName="label.labelName" :color="label.color" :edit="true" @removeLabel="removeLabel"></app-header-button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</script>

	<script type="text/x-template" id="app-header-template">
		<div class="row bg-secondary pt-1 pb-1">
			<div class="col-10">
				<div class="row">
					<app-header-button @clicked="ann" v-for="label in labels" :labelName="label.labelName" :color="label.color"></app-header-button>
				</div>
			</div>
			<div class="col-2">
				<app-header-editmodal @addLabelSave="addLabelSave" @removeLabel="removeLabel" :labels="labels"></app-header-editmodal>
			</div>
		</div>
	</script>

	<script type="text/x-template" id="app-text-template">
		<div class="mt-1" style="font-size:20px;line-height:1.6;" @click="selected">
			<span v-for="ann in slices" :style="styles(ann.color)" class="inline">[[ text.slice(ann.start_offset,ann.end_offset) ]]<a v-if="ann.check" @click="remove(ann)" aria-label="Close" class="text-danger" style="cursor:pointer;"><span aria-hidden="true">&times;</span></a></span>
		</div>
	</script>

	<script type="text/x-template" id="app-template">
		<div class="w-auto" style="background-color:aliceblue;">
			<app-header class="row mx-1" @update="annotate" @labelupdate="labelUpdate" @removelabel="removeLabel" :labels="labels"></app-header>
			<app-text class="mx-1 bg-white text-left" :text="text" @add-label="addLabel" @clear-label="clearLabel" ref="apptext" :anns="anns"></app-text>
			<div class="mt-1 mx-1">
				<form method="post">
					{% csrf_token %}
					<a href="{% url 'acti:tweet_list' mode='check' %}" class="btn btn-primary btn-sm" @click="save">Save</a>
					<a href="{% url 'acti:tweet_list' mode='check' %}" class="btn btn-secondary btn-sm">Back</a>
				</form>
			</div>
		</div>
	</script>
{% endblock content %}

{% block javascript %}
<script type="text/javascript" src="{% static '/js/acti/vue.min.js' %}"></script>
<script type="text/javascript" src="{% static '/js/acti/annotation_labeling.js' %}"></script>
{% endblock %}

apps/acti/templates/acti/tweet_list.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% include "acti/menu.html" %}
{% include "twitter/searchBar.html" %}
<div>
    <h4 class="mt-4 border-bottom">Target List</h4>
    <table id="tweet" class="table table-sm table-bordered" style="width: 100%;table-layout: fixed;">
        <thead class="thead-light">
        <tr>
            <th scope="col" style="width:15%;">User</th>
            <th scope="col" style="width:50%;">Tweet</th>
            <th scope="col" style="width:15%;">Date (JST)</th>
            <th scope="col" style="width:20%;">Controller</th>
        </tr>
        </thead>
        <tbody>
        {% for tweet in　tweets %}
        <tr>
            <td class="text-truncate">{{ tweet.tweet.screen_name }}</td>
            <td class="text-truncate">{{ tweet.tweet.text }}</td>
            <td>{{ tweet.tweet.datetime }}</td>
            <td>
                <a href="{% url 'acti:tweet_annotation' tweet_id=tweet.tweet.id %}" class="btn btn-outline-primary btn-sm">Annotation</a>
                <a href="{% url 'acti:tweet_view' tweet_id=tweet.tweet.id %}" class="btn btn-outline-info btn-sm">View</a>
            </td>
        </tr>
        {% empty %}

        {% endfor %}
        </tbody>
    </table>
    {% include "acti/page.html" %}
</div>
{% endblock content %}

{% block javascript %}
<script type="text/javascript" src="{% static '/js/acti/jquery.tablesorter.min.js' %}"></script>
<script type="text/javascript">
$(window).load(function() {
    $('#tweet').tablesorter();
});
</script>
{% endblock javascript %}

apps/acti/templates/acti/tweet_view.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}ACTI{% endblock title %}

{% block content %}
{% include "acti/menu.html" %}
	<div id="main" class="container">
		<app></app>
	</div>

	<script type="text/javascript">
		var text = "{{ text|safe|escapejs }}";
		var labels = {{ labels|safe|escape }};
		var annotation = {{ annotation|safe|escape }};
		const twkey = "{{tweet_id}}";
	</script>

	<script type="text/x-template" id="app-header-button-template">
		<div class="m-1">
			<button class="btn btn-sm" style="font-weight: bold;" :style="styleColor">[[ labelName ]]</button>
			<a v-if="edit" aria-label="Close" class="text-danger" style="cursor:pointer;"><span aria-hidden="true">&times;</span></a>
		</div>
	</script>

	<script type="text/x-template" id="app-header-template">
		<div class="row bg-secondary pt-1 pb-1">
			<div class="col-10">
				<div class="row">
					<app-header-button v-for="label in labels" :labelName="label.labelName" :color="label.color"></app-header-button>
				</div>
			</div>
			<div class="col-2">
				<app-header-editmodal :labels="labels"></app-header-editmodal>
			</div>
		</div>
	</script>

	<script type="text/x-template" id="app-text-template">
		<div class="mt-1" style="font-size:20px;line-height:1.6;" @click="selected">
			<span v-for="ann in slices" :style="styles(ann.color)" class="inline">[[ text.slice(ann.start_offset,ann.end_offset) ]]</span>
		</div>
	</script>

	<script type="text/x-template" id="app-template">
		<div class="w-auto" style="background-color:aliceblue;">
			<app-header class="row mx-1" :labels="labels"></app-header>
			<app-text class="mx-1 bg-white text-left" :text="text" ref="apptext" :anns="anns"></app-text>
			<div class="mt-1 mx-1">
				<a href="{% url 'acti:tweet_list' mode='check' %}" class="btn btn-secondary btn-sm">Back</a>
			</div>
		</div>
	</script>
{% endblock content %}

{% block javascript %}
<script type="text/javascript" src="{% static '/js/acti/vue.min.js' %}"></script>
<script type="text/javascript" src="{% static '/js/acti/annotation_labeling.js' %}"></script>
{% endblock %}